### ISSUE TITLE
Deleting COVID update messages breaks the bot when it's doing future Corona Updates; Add corona delete command

### ISSUE THREAD

**Issue by noticemechris** [Nobelz/SpartanBot#21]
Not exactly sure what happened today, but if a mod deletes the most recent spartan bot covid message it inhibits the bot's ability to make more posts in the future with ``!!corona update``. Bot will not post anything at all, but other parts seem to work.

**Comment by Nobelz** [comment]
Thank you for the issue submission. This is should be fixed in the most recent commit (fe5acbc).

That being said, I think it would be prudent to add a corona delete function to delete the message so the mods won't have to delete this manually. I'm adding this to the to-do list.
- [ ] Add `!!corona delete`

**Comment by Nobelz** [comment]
Closing issue. Problem should be resolved. Please open if issue persists.
